version: "3"

services:
  database:
      image: mariadb
      environment:
          - MYSQL_ROOT_PASSWORD=Temporal01
          - MYSQL_DATABASE=Formacion-Sinensia
      volumes:
          - ./database:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin
      environment:
          - PMA_ARBITRARY:1
          - PMA_HOST=database
          - MYSQL_ROOT_PASSWORD=Temporal01
      restart: always
      ports:
          - 8082:80
      volumes:
          - /persistente
      depends_on:
          - database
