version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: Luis
      WORDPRESS_DB_PASSWORD: Temporal01
      WORDPRESS_DB_NAME: luis_db
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: luis_db
      MYSQL_USER: Luis
      MYSQL_PASSWORD: Temporal01
      MYSQL_ROOT_PASSWORD: Temporal01
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY:1
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=Temporal01
    restart: always
    ports:
      - 8082:80
    depends_on:
      - db

volumes:
  wordpress:
  db:
